# Generated by Django 3.0.14 on 2021-08-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_activo',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='UsuarioAuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='core.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
