# Generated by Django 3.0.14 on 2021-08-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210802_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioAuthToken',
        ),
    ]
