# Generated by Django 3.0.14 on 2021-08-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id_centro_costo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_centro_costo', models.BigIntegerField()),
                ('nombre_centro_costo', models.CharField(default='', max_length=25)),
                ('codigo_cc', models.BigIntegerField()),
            ],
        ),
    ]
