# Generated by Django 3.0.14 on 2021-08-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_Proveedor',
            fields=[
                ('id_contacto_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Proveedor')),
            ],
        ),
    ]
