# Generated by Django 3.0.14 on 2021-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contacto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='idioma_en',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(default='', max_length=25),
        ),
    ]
