# Generated by Django 3.0.14 on 2021-08-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210826_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_es', models.CharField(default='', max_length=25)),
                ('unidad_en', models.CharField(default='', max_length=25)),
                ('siglas', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
