# Generated by Django 3.0.14 on 2021-08-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Categoria',
            fields=[
                ('id_inventario_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('inventario_categoria', models.CharField(default='', max_length=120)),
                ('inventario_categoria_notas', models.CharField(default='', max_length=500)),
                ('inventario_categoria_estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EstatusUsuario')),
            ],
        ),
    ]
