# Generated by Django 3.0.14 on 2021-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(default='', max_length=25)),
                ('mes', models.CharField(default='', max_length=25)),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
            ],
        ),
    ]
