# Generated by Django 3.0.14 on 2021-09-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaHoras',
            fields=[
                ('id_jornada_horas', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(default='', max_length=25)),
                ('hora', models.TimeField()),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Jornada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
    ]
