# Generated by Django 3.0.14 on 2021-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jornadahoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_Categoria_Estatus',
            fields=[
                ('id_equipo_categoria_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_categoria_estatus_en', models.CharField(max_length=25)),
                ('equipo_categoria_estatus_es', models.CharField(max_length=25)),
            ],
        ),
    ]
