# Generated by Django 3.0.14 on 2022-02-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220222_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Sesion',
            fields=[
                ('id_usuario_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(max_length=20)),
                ('hora_inicio', models.CharField(max_length=20)),
                ('fecha_cierre', models.CharField(max_length=20)),
                ('hora_cierre', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Mro',
            fields=[
                ('id_usuario_mro', models.AutoField(primary_key=True, serialize=False)),
                ('gastos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Nivel_Gastos')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Nivel_Mro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Evento',
            fields=[
                ('id_usuario_evento', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.CharField(max_length=100)),
                ('elemento', models.CharField(max_length=100)),
                ('anterior', models.CharField(max_length=100)),
                ('nuevo', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=20)),
                ('usaurio_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Usuario')),
                ('usuario_modifica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Contrasena',
            fields=[
                ('id_usuario_contrasena', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=250)),
                ('fecha', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Activoeam',
            fields=[
                ('id_usuario_activoeam', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisicion_Aprovada',
            fields=[
                ('id_requisicion_aprovada', models.AutoField(primary_key=True, serialize=False)),
                ('id_aprovacion_1', models.IntegerField()),
                ('id_aprovacion_2', models.IntegerField()),
                ('id_aprovacion_3', models.IntegerField()),
                ('requisicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Requisicion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor_Giro',
            fields=[
                ('id_proveeor_giro', models.AutoField(primary_key=True, serialize=False)),
                ('giro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Giro')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_De_Compra_Aprovada',
            fields=[
                ('id_orden_compra_aprovada', models.AutoField(primary_key=True, serialize=False)),
                ('id_aprovacion_1', models.IntegerField()),
                ('id_aprovacion_2', models.IntegerField()),
                ('id_aprovacion_3', models.IntegerField()),
                ('orden_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Prov',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visto', models.IntegerField()),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('prov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Prod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Presupuesto_Costos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oc_presupuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Mensaje_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_mensaje', models.IntegerField()),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Mensaje_Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_mensaje', models.IntegerField()),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Oc_Chat',
            fields=[
                ('id_oc_chat', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=45)),
                ('hora', models.CharField(max_length=45)),
                ('timestamp', models.CharField(max_length=45)),
                ('mensaje', models.CharField(max_length=255)),
                ('envia', models.IntegerField()),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Cotizacion')),
                ('prov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Proveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Producto_Recibido',
            fields=[
                ('id_estado_producto_recibido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('estado_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Estado_Material')),
                ('estado_paquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Estado_Paquete')),
                ('estado_sello', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Estado_Sello')),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Orden_De_Compra_Producto')),
            ],
        ),
    ]
